spring:
  profiles: cloud
  application:
    name: spring-boot-meetup-service
  data:
    cassandra:
      keyspace-name: meetups
      contact-points: ${vcap.services.cassandra.credentials.node_ips[0]}
      password: ${vcap.services.cassandra.credentials.password}
      username: ${vcap.services.cassandra.credentials.username}
---
spring:
  profiles: dev
  data:
    cassandra:
      keyspace-name: meetups
      contactpoints: localhost
      user: cassandra
      pword: cassandra

#---
#spring:
#  profiles: cloud
#  data:
#    cassandra:
#      contactpoints: ${vcap.services.p-dse-cassandra-sb.credentials.node_ips[0]}
#      user: ${vcap.services.p-dse-cassandra-sb.credentials.username}
#      pword: ${vcap.services.p-dse-cassandra-sb.credentials.password}
#      port: ${vcap.services.p-dse-cassandra-sb.credentials.cqlsh_port}
#

